import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const app = await readFile(new URL("../src/App.jsx", import.meta.url), "utf8");
const data = await readFile(new URL("../src/data.js", import.meta.url), "utf8");
const panoramaLinks = await readFile(new URL("../src/panorama-links.js", import.meta.url), "utf8");
const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
const styles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
const inventoryScript = await readFile(new URL("../scripts/inventory-site.mjs", import.meta.url), "utf8");
const importer = await readFile(new URL("../scripts/import-current-content.mjs", import.meta.url), "utf8");
const compiler = await readFile(new URL("../scripts/compile-content.mjs", import.meta.url), "utf8");
const adminGuide = await readFile(new URL("../docs/content-admin-guide.md", import.meta.url), "utf8");
const multiImageArticle = await readFile(new URL("../content/news/fa2-26.md", import.meta.url), "utf8");
test("all required client routes are declared", () => { for (const route of ["/meteo", "/news", "/club", "/chronik", "/mitglied", "/fluggebiet", "/fluggebiet/startplaetze", "/fluggebiet/landeplaetze", "/fluggebiet/sicherheit", "/fluggebiet/grund", "/fotos", "/kontakt"]) assert.match(app, new RegExp(`"${route}"`)); });
test("anniversary UI is controlled by one named config flag", () => { assert.match(data, /showAnniversary: true/); assert.match(app, /if \(!CONFIG\.showAnniversary\) return null/); assert.match(app, /CONFIG\.showAnniversary &&/); assert.doesNotMatch(app, /toplogo|toplogo-trimmed|<img src=\{images\.logo\}/); const wordmark = app.match(/className="wordmark">([\s\S]*?)<\/AppLink>/)?.[1] || ""; assert.match(wordmark, /Jungfrau-Tächi/); assert.match(wordmark, /GRINDELWALD/); assert.doesNotMatch(wordmark, /(?:\b50\b|1976–2026|<img)/); });
test("shared flight-site viewer is local and preserves all panorama interactions", () => { for (const scene of ["first", "waldspitz", "maennlichen", "muerren", "grund", "bodmi", "stechelberg", "lauterbrunnen"]) assert.match(data, new RegExp(`panorama\\(\"${scene}\"`)); for (const label of ["Grindelwald, First", "Grindelwald, Grund", "Grindelwald, Bodmi", "Stechelberg, Schilthornbahn", "Lauterbrunnen"]) assert.match(data, new RegExp(label)); assert.match(data, /assets\/panoramas/); assert.doesNotMatch(data, /tourUrl:.*jungfrau-taechi\.ch/); assert.match(app, /function LocalPanorama/); assert.match(app, /window\.pannellum\.viewer/); assert.match(app, /type: "cubemap"/); assert.match(app, /role="tablist"/); assert.match(app, /aria-selected=/); assert.match(app, /requestFullscreen/); assert.match(app, /Neu laden/); assert.doesNotMatch(app, /<iframe/); });
test("the unified explorer exposes all thirteen locally hosted scenes and source-derived cross-links", () => { for (const scene of ["airtime-west", "airtime-ost", "airtime-winter", "airtime-max", "airtime-stechelberg"]) assert.match(data, new RegExp(`panorama\\(\"${scene}\"`)); assert.match(data, /export const flightScenes/); assert.match(data, /export const flightSceneGroups/); assert.match(data, /panoramaLinks/); assert.match(app, /function FlightExplorer/); assert.match(app, /13 Standorte in einer Ansicht/); assert.match(app, /createSceneLinkHotspot/); assert.doesNotMatch(app, /Weiter im Fluggebiet|flight-connections/); assert.match(app, /Nur gewählte Szene geladen/); assert.doesNotMatch(app, /Aufnahmen 2015|Historische Bestandsaufnahme/); });
test("source-derived area markings use clipped spherical projection and are enabled by default", () => { for (const label of ["Landeplatz Grund", "ACHTUNG ZAUN", "Landeplatz Bodmi", "Landeplatz Stechelberg", "Landeplatz Lauterbrunnen"]) assert.match(panoramaLinks, new RegExp(label)); assert.equal((panoramaLinks.match(/"vertices": \[/g) || []).length, 24); assert.match(data, /showPanoramaAreas: true/); assert.match(app, /useState\(CONFIG\.showPanoramaAreas\)/); assert.match(app, /aria-pressed=\{showAreas\}/); assert.match(app, /site\.areas\.flatMap/); assert.match(app, /function projectSphericalPolygon/); assert.match(app, /const near = 0\.02/); assert.match(app, /clipPolygon\(projected/); assert.match(app, /createElementNS\("http:\/\/www\.w3\.org\/2000\/svg", "svg"\)/); assert.match(styles, /\.pano-area-overlay/); assert.match(styles, /\.pnlm-hotspot-base\{z-index:4/); });
test("panorama information markers expose webcams and clearly labelled demo weather readings", () => { assert.match(app, /function createInfoHotspot/); assert.match(app, /function panoramaInfoMarkers/); assert.match(app, /Demo-Messwert/); assert.match(app, /Original-Panorama öffnen/); assert.match(app, /onOpenMeteo/); assert.match(styles, /\.pano-info-hotspot/); });
test("official SHV Grindelwald facts and document are integrated", () => { for (const value of ["2120 m ü. M.", "46.6575, 8.0551", "Ost bis Südwest", "950 m ü. M.", "46.6202, 8.0294", "1100 m ü. M.", "46.6287, 8.0436", "Schwer (im Winter einfach)"]) assert.ok(data.includes(value), `missing SHV fact: ${value}`); assert.match(data, /shv-fluggebiet-grindelwald\.pdf/); assert.match(data, /airspace\.shv-fsvl\.ch/); assert.match(app, /function SiteFacts/); assert.match(app, /SHV Infotafel Grindelwald/); assert.match(app, /DABS vor jedem Flug prüfen/); });
test("migrated route data retains source URLs", () => { for (const path of ["sites/news", "sites/club", "sites/chronik", "sites/mitglied", "sites/fluggebiet", "sites/grund", "sites/fotoreports", "sites/kontakt"]) assert.match(data, new RegExp(path)); });
test("runtime content images use the Pages-aware asset helper and detail-aware titles", () => { assert.match(data, /generatedNews\.map/); assert.match(data, /contentAsset\(item\.coverImage\)/); assert.match(app, /function titleForPath/); assert.match(app, /document\.title = title \?/); });
test("hero, generated galleries, and DABS contracts use the corrected destinations", () => { assert.match(data, /hero: localAsset\("\/assets\/source\/hero-flight\.jpg"\)/); assert.match(data, /generatedPhotoReports\.map/); assert.match(data, /https:\/\/www\.skybriefing\.com\/de\//); assert.match(app, /<span>Jungfrau-Tächi<\/span><small>GRINDELWALD<\/small>/); });
test("static metadata, anniversary map, and mobile navigation contracts are accessible", () => { assert.match(html, /<html lang="de">/); assert.match(html, /<title>Jungfrau-Tächi Grindelwald<\/title>/); assert.match(app, /alt="Karte der Jubiläums-Challenge in der Jungfrau-Region"/); assert.match(styles, /\.primary-nav\{position:relative\}/); assert.match(styles, /\.primary-nav nav\{left:0!important;right:0!important;top:100%!important\}/); });
test("primary pages share the compact Meteo-derived spacing rhythm", () => { for (const token of ["--page-head-start", "--page-head-end", "--section-space", "--page-end-space"]) assert.ok(styles.includes(token)); assert.match(styles, /\.page-intro\{padding-block:var\(--page-head-start\) var\(--page-head-end\)\}/); assert.match(styles, /\.flight-explorer-intro>\.shell\{[^}]*padding-block:2\.5rem 2rem/); assert.match(styles, /\.club-intro\{padding-block:3\.25rem\}/); });
test("homepage prioritizes flight preparation, the next event, unique news and visual discovery", () => { for (const phrase of ["Fluggebiet entdecken", "Wind &amp; Meteo", "Start- &amp; Landeplätze", "Nächster Clubtermin", "Aktuell aus dem Club", "Erlebnisse und Clubgeschichte"]) assert.ok(app.includes(phrase), `missing homepage priority: ${phrase}`); for (const className of ["home-banner", "home-flightdesk", "home-next-event", "home-news", "home-discover"]) assert.match(app, new RegExp(`className=\"[^\"]*\\b${className}\\b`), `missing homepage section: ${className}`); assert.ok(app.indexOf('className="home-flightdesk"') < app.indexOf('className="home-next-event"')); assert.ok(app.indexOf('className="home-next-event"') < app.indexOf('className="shell home-news"')); assert.doesNotMatch(app, /activityLinks/); for (const selector of [".home-flightdesk-grid", ".home-next-event-grid", ".home-news-grid", ".home-discover-grid"]) assert.ok(styles.includes(selector), `missing responsive homepage style: ${selector}`); });
test("secondary pages use one compact image-backed navy banner", () => { assert.match(app, /function SectionIntro\([\s\S]*className="page-banner"/); for (const expression of ["image={news[0]?.image || images.hero}", "image={photoReports[0]?.image || images.hero}", "title=\"Chronik\"", "title=\"Vorstand und Kontakt\""]) assert.ok(app.includes(expression), `missing page banner contract: ${expression}`); assert.match(styles, /\.page-banner\{position:relative;display:flex;min-height:230px/); assert.match(styles, /var\(--page-banner-image\)/); assert.match(styles, /\.page-banner\+\.shell\{margin-top:2rem\}/); });
test("club overview consolidates the complete migrated story archive and puts the agenda first", () => { for (const exportName of ["clubPurposes", "clubPortrait", "clubStories", "clubProgramme", "chronology"]) assert.match(data, new RegExp(`export const ${exportName}`)); for (const phrase of ["13 Flugenthusiasten", "Erhaltung des Fluggebietes", "Der Matratzenboom", "Speedrun und Race to Goal", "Gleitschirmstadion Grindelwald", "Blätz und das schlechte Material", "Übernachtung «on Ice»", "Erster Mönch-Überflug", "Clubfliegen First", "automatische Wetterstation"]) assert.ok(data.includes(phrase), `missing migrated club content: ${phrase}`); const storySource = data.match(/export const clubStories = \[([\s\S]*?)\n\];\nexport const clubProgramme/)?.[1] || ""; assert.equal((storySource.match(/author:/g) || []).length, 15); const chronologySource = data.match(/export const chronology = \[([\s\S]*?)\n\];/)?.[1] || ""; assert.equal((chronologySource.match(/\{ year:/g) || []).length, 30); for (const anchor of ["#portrait", "#auftrag", "#geschichte", "#clubleben", "#stories"]) assert.ok(app.includes(anchor)); assert.match(app, /Vollständiges Portrait lesen/); assert.match(app, /Vollständige Chronik/); assert.match(app, /storyCount} Geschichten in drei Kapiteln/); assert.ok(app.indexOf('className="club-agenda"') < app.indexOf('className="shell club-portrait"'), "agenda must precede the club portrait"); assert.match(styles, /\.club-purpose-grid/); assert.match(styles, /\.club-agenda-grid/); assert.match(styles, /\.club-story-chapters/); });
test("every page family uses a clear branded opening", () => { for (const expression of ["home-banner", "page-banner meteo-intro", "page-banner club-intro", "function DetailIntro", "flight-explorer-intro", "function SectionIntro"]) assert.ok(app.includes(expression), `missing branded opening: ${expression}`); assert.match(data, /flightAreaHero: localAsset\("\/assets\/panoramas\/first\/3\.jpg"\)/); });
test("board cards retain public contact details and replaceable portraits", () => { for (const value of ["dres.egger@gmail.com", "+41 79 722 86 65", "peter-zurbuchen@bluewin.ch", "jungfrautaechi@gmail.com", "info@pascalimhof.com"]) assert.ok(data.includes(value), `missing board contact: ${value}`); assert.match(data, /board-placeholder\.png/); assert.match(app, /mailto:/); assert.match(app, /tel:/); assert.doesNotMatch(app, /Persönliche Kontaktdaten werden vor der Veröffentlichung/); });
test("inventory accepts both canonical host spellings for internal links", () => { assert.match(inventoryScript, /replace\(\/\^www\\\.\/, ""\)/); assert.match(inventoryScript, /filter\(isClubUrl\)/); });
test("inventory distinguishes unavailable retained links from verified empty link sets", () => { assert.match(inventoryScript, /internalLinksStatus/); assert.match(inventoryScript, /availability: "unavailable"/); assert.match(inventoryScript, /page\.internalLinks = null/); assert.match(inventoryScript, /"unavailable"/); assert.match(inventoryScript, /availability: "complete"/); });
test("public UI has no migration provenance or original-content links", () => { for (const phrase of ["Quelle:", "Zum Original", "Challenge im Original", "sourceUrl}>Zum Original"]) assert.doesNotMatch(app, new RegExp(phrase)); assert.doesNotMatch(data, /newsfeed\/(?:eigertour9a|fa2_26|hf26_1_5|challenge50)/); });
test("client navigation moves focus to the new page heading", () => { assert.match(app, /<h1 tabIndex="-1">/); assert.match(app, /document\.querySelector\("#inhalt h1"\)\?\.focus\(\)/); });
test("meteo prototype exposes the reviewed station hierarchy, Grund placeholder, live webcams, mock history and safety labels", () => {
  for (const station of ["Grindelwald First", "Schmidigen-Bidmeren", "Itramen", "Männlichen", "Russisprung", "Interlaken", "Stechelberg", "Meiringen"]) assert.match(data, new RegExp(station));
  const catalog = data.match(/export const windStationCatalog = \[([\s\S]*?)\n\];/)?.[1] || "";
  assert.equal((catalog.match(/\{ id:/g) || []).length, 29);
  for (const planned of ["planned-grindelwald-grund", "Grindelwald Grund", "Landeplatz", "Geplant"]) assert.ok(data.includes(planned));
  for (const camera of ["Grindelwald-First", "Eigergletscher", "Männlichen", "Kleine Scheidegg", "Grindelwald Terminal"]) assert.ok(data.includes(camera));
  assert.equal((data.match(/roundshot\.com\/cams\/\d+\/medium/g) || []).length, 5);
  assert.equal((data.match(/focus: 0\./g) || []).length, 5);
  assert.match(app, /function PlannedStationCard/);
  assert.match(app, /function WebcamCard/);
  assert.match(app, /method: "HEAD"/);
  assert.match(app, /Last-Modified/);
  assert.match(app, /Europe\/Zurich/);
  assert.match(app, /activeWebcamIndex/);
  assert.match(app, /Original-Webcam im Vollbild ↗/);
  assert.match(app, /onPointerDown=\{startDrag\}/);
  assert.match(app, /setPointerCapture/);
  assert.match(app, /moveWebcam/);
  assert.match(app, /viewportRef/);
  assert.match(app, /scrollLeft/);
  assert.match(app, /camera\.focus/);
  assert.match(app, /Vorherige Webcam/);
  assert.match(app, /Nächste Webcam/);
  assert.match(app, /camera=\{activeWebcam\}/);
  assert.ok(app.indexOf('className="webcam-panel"') < app.indexOf('className="dabs-panel"'), "DABS must follow the full-width webcam panel");
  assert.match(styles, /\.meteo-secondary-grid\{display:grid;grid-template-columns:minmax\(0,1fr\)/);
  assert.doesNotMatch(app, />Live-Panorama</);
  assert.match(app, /Noch keine Messwerte/);
  assert.match(app, /5 aktiv · 1 geplant/);
  assert.match(app, /Bilder neu laden/);
  assert.match(app, /© Jungfraubahnen · Roundshot/);
  assert.match(app, /primaryStations = meteoStations\.slice\(0, 5\)/);
  assert.match(app, /regionalStations = meteoStations\.slice\(5\)/);
  assert.match(app, /24 weitere Stationen anzeigen|regionalStations\.length/);
  assert.match(app, /aria-expanded=\{showRegionalStations\}/);
  assert.match(app, /aria-controls="regional-wind-stations"/);
  assert.match(app, /Letzte Messungen/);
  assert.match(app, /Mockdaten aktualisiert/);
  assert.match(app, /nicht für Flugentscheidungen geeignet/);
  assert.match(app, /Offizielles DABS öffnen/);
  assert.match(styles, /\.planned-station-card/);
  assert.match(styles, /\.wind-history\{display:grid;grid-template-columns:repeat\(4/);
  assert.match(styles, /\.wind-grid\.is-regional/);
  assert.match(styles, /\.webcam-panorama-viewport\{[^}]*aspect-ratio:16\/7;[^}]*overflow-x:auto/);
  assert.match(styles, /\.webcam-panel,\.webcam-gallery\{width:100%;min-width:0;max-width:100%\}/);
  assert.match(styles, /\.webcam-gallery\{overflow:hidden/);
  assert.match(styles, /\.webcam-panorama-viewport\{[^}]*width:100%;[^}]*max-width:100%/);
  assert.match(styles, /\.webcam-panorama-viewport img\{[^}]*width:auto;[^}]*max-width:none;[^}]*height:100%/);
  assert.match(styles, /\.webcam-panorama-viewport\{aspect-ratio:16\/9\}/);
});
test("inventory rejects missing canonicals and clears legacy undefined values", () => { assert.match(inventoryScript, /if \(!value\) return null/); assert.match(inventoryScript, /page\.canonical\?\.endsWith\("\/undefined"\)/); assert.match(inventoryScript, /page\.canonical = null/); assert.match(inventoryScript, /canonicalStatus/); });
test("complete news and photo archives use reusable internal detail routes", () => { assert.match(app, /function NewsArticlePage/); assert.match(app, /function PhotoReportPage/); assert.match(app, /path\.startsWith\("\/news\/"\)/); assert.match(app, /path\.startsWith\("\/fotos\/"\)/); assert.match(app, /dangerouslySetInnerHTML/); assert.match(app, /photo-thumbnails/); assert.match(importer, /newsPages/); assert.match(importer, /\.photogalleryTable/); assert.match(compiler, /generatedNews/); });
test("multi-image news uses the same interactive gallery viewer as photo reports", () => { assert.match(app, /function GalleryViewer/); assert.match(app, /<GalleryViewer images=\{gallery\} title=\{article\.title\}/); assert.match(app, /<GalleryViewer images=\{report\.gallery\} title=\{report\.title\}/); assert.equal((multiImageArticle.match(/  - src:/g) || []).length, 13); assert.match(styles, /\.news-gallery-module/); });
test("club admins can add repository content without editing React", () => { for (const phrase of ["content/templates/news.md", "content/templates/photo-report.md", "Branch `stage`", "Pull Request", "Decap CMS"]) assert.match(adminGuide, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))); });
