import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { Readable } from 'node:stream';
import { createMarkerSaveMiddleware, markerEditorPlugin } from '../scripts/marker-editor-plugin.mjs';

test('local editor saves selected entries, preserves other edits, serializes writes and rejects unsafe requests', async t => {
  const root = await mkdtemp(join(tmpdir(), 'taechi-marker-test-'));
  await mkdir(join(root, 'src'));
  const webcamFile = join(root, 'src/panorama-webcams.json');
  const overrideFile = join(root, 'src/panorama-marker-overrides.json');
  const initial = { 'airtime-west': { baeregg: { yaw: 7, pitch: 8, provisional: true }, first: { yaw: 1, pitch: 2 } }, grund: { terminal: { yaw: 9, pitch: 10 } } };
  await writeFile(webcamFile, JSON.stringify(initial));
  await writeFile(overrideFile, '{}');
  const middleware = createMarkerSaveMiddleware(root);
  const server = createServer((req, res) => middleware(req, res, () => { res.writeHead(404); res.end(); }));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { await new Promise(resolve => server.close(resolve)); await rm(root, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const post = (data, headers = {}) => fetch(`${base}/__local/marker-position`, { method: 'POST', headers: { Origin: base, 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(data) });
  const data = { sceneId: 'airtime-west', kind: 'webcam', id: 'baeregg', position: { yaw: 0, pitch: -3 } };
  assert.equal((await post(data)).status, 200);
  const changed = JSON.parse(await readFile(webcamFile, 'utf8'));
  assert.deepEqual(changed['airtime-west'].baeregg, { yaw: 0, pitch: -3, provisional: false });
  assert.deepEqual(changed.grund, initial.grund);
  assert.deepEqual(changed['airtime-west'].first, initial['airtime-west'].first);
  const results = await Promise.all([post({ ...data, kind: 'wind', id: 'fanet-BA-4' }), post({ ...data, kind: 'panoramas', id: 'grund' })]);
  assert.deepEqual(results.map(r => r.status), [200, 200]);
  const overrides = JSON.parse(await readFile(overrideFile, 'utf8'));
  assert.ok(overrides['airtime-west'].wind['fanet-BA-4']);
  assert.ok(overrides['airtime-west'].panoramas.grund);
  const beforeRejected = await readFile(webcamFile, 'utf8');
  for (const bad of [{ ...data, sceneId: '__proto__' }, { ...data, id: '../../anything' }, { ...data, kind: 'arbitrary-file' }, { ...data, position: { yaw: 181, pitch: 0 } }]) assert.equal((await post(bad)).status, 400);
  assert.equal((await post(data, { Origin: 'https://example.com' })).status, 403);
  assert.equal((await post(data, { Origin: '' })).status, 403);
  assert.equal((await post(data, { 'Sec-Fetch-Site': 'cross-site' })).status, 403);
  assert.equal((await post(data, { 'Content-Type': 'text/plain' })).status, 415);
  const remote = Readable.from([JSON.stringify(data)]);
  Object.assign(remote, { url: '/__local/marker-position', method: 'POST', socket: { remoteAddress: '192.168.1.2' }, headers: { origin: base, host: new URL(base).host, 'content-type': 'application/json' } });
  let status;
  await middleware(remote, { writeHead: code => { status = code; }, end() {} }, () => {});
  assert.equal(status, 403);
  assert.equal(await readFile(webcamFile, 'utf8'), beforeRejected);
  assert.equal(markerEditorPlugin().apply, 'serve');
});
