import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { validateRecord, localMediaPath } from "./content-validation.mjs";
import path from "node:path";
import matter from "gray-matter";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";

const root = path.resolve(".");
const output = path.join(root, "src/generated-content.js");
let unavailableArchiveImages = 0;
const mediaExists = async (src) => {
  if (!src) return false;
  const relative = localMediaPath(src);
  if (!relative) return true;
  try { await access(path.join(root, "public", relative)); return true; } catch { return false; }
};
const normalizeDate = (value) => {
  if (value instanceof Date) return Number.isNaN(value.valueOf()) ? "" : value.toISOString().slice(0, 10);
  return /^(\d{4}-\d{2}-\d{2})(?:T.*)?$/.exec(String(value || ""))?.[1] || "";
};
const cleanHtml = (markdown) => sanitizeHtml(marked.parse(markdown || ""), {
  allowedTags: ["p", "br", "strong", "em", "b", "i", "h2", "h3", "h4", "ul", "ol", "li", "blockquote", "a", "hr"],
  allowedAttributes: { a: ["href", "title"] },
  allowedSchemes: ["http", "https", "mailto"],
  transformTags: { a: sanitizeHtml.simpleTransform("a", { rel: "noreferrer" }) },
});
const readCollection = async (directory) => {
  await mkdir(directory, { recursive: true });
  const files = (await readdir(directory)).filter((file) => file.endsWith(".md")).sort();
  const records = await Promise.all(files.map(async (file) => {
    const parsed = matter(await readFile(path.join(directory, file), "utf8"));
    if (parsed.data.draft === true) return null;
    const record = { ...parsed.data, date: normalizeDate(parsed.data.date), bodyHtml: cleanHtml(parsed.content) };
    const issues = validateRecord(record);
    if (issues.length) throw new Error(`${file}: ${issues.join("; ")}`);
    const legacy = /^https?:\/\/(www\.)?jungfrau-taechi\.ch\//.test(record.sourceUrl || "");
    const gallery = [];
    for (const [index, image] of (record.gallery || []).entries()) {
      if (!await mediaExists(image?.src)) {
        if (!legacy) throw new Error(`${file}: missing gallery image ${image?.src || "(empty path)"}`);
        unavailableArchiveImages++; continue;
      }
      gallery.push({ ...image, alt: image.alt?.trim() || `${record.title} – Bild ${index + 1}` });
    }
    if (record.coverImage && !await mediaExists(record.coverImage)) {
      if (!legacy) throw new Error(`${file}: missing cover image ${record.coverImage}`);
      unavailableArchiveImages++;
      record.coverImage = "";
    }
    return { ...record, gallery };
  }));
  const published = records.filter(Boolean);
  const seen = new Set();
  for (const record of published) { if (seen.has(record.slug)) throw new Error(`Duplicate slug: ${record.slug}`); seen.add(record.slug); }
  return published;
};
const newsArticles = (await readCollection(path.join(root, "content/news"))).sort((a, b) => String(b.date).localeCompare(String(a.date)) || a.title.localeCompare(b.title, "de"));
const photoReports = (await readCollection(path.join(root, "content/photo-reports"))).sort((a, b) => String(b.date).localeCompare(String(a.date)) || a.title.localeCompare(b.title, "de"));
await writeFile(output, `// Generated by scripts/compile-content.mjs. Edit content/*.md, not this file.\nexport const generatedNews = ${JSON.stringify(newsArticles, null, 2)};\nexport const generatedPhotoReports = ${JSON.stringify(photoReports, null, 2)};\n`);
console.log(`Content compiled: ${newsArticles.length} news articles and ${photoReports.length} photo reports.`);
if (unavailableArchiveImages) console.warn(`${unavailableArchiveImages} unavailable archive image references omitted; original records retained for recovery.`);
