import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";

const root = path.resolve(".");
const output = path.join(root, "src/generated-content.js");
const cleanHtml = (markdown) => sanitizeHtml(marked.parse(markdown || ""), {
  allowedTags: ["p", "br", "strong", "em", "b", "i", "h2", "h3", "h4", "ul", "ol", "li", "blockquote", "a", "hr"],
  allowedAttributes: { a: ["href", "title"] },
  allowedSchemes: ["http", "https", "mailto"],
  transformTags: { a: sanitizeHtml.simpleTransform("a", { rel: "noreferrer" }) },
});
const readCollection = async (directory) => {
  await mkdir(directory, { recursive: true });
  const files = (await readdir(directory)).filter((file) => file.endsWith(".md")).sort();
  return Promise.all(files.map(async (file) => {
    const parsed = matter(await readFile(path.join(directory, file), "utf8"));
    return { ...parsed.data, bodyHtml: cleanHtml(parsed.content) };
  }));
};
const newsArticles = (await readCollection(path.join(root, "content/news"))).sort((a, b) => String(b.date).localeCompare(String(a.date)) || a.title.localeCompare(b.title, "de"));
const photoReports = (await readCollection(path.join(root, "content/photo-reports"))).sort((a, b) => String(b.date).localeCompare(String(a.date)) || a.title.localeCompare(b.title, "de"));
await writeFile(output, `// Generated by scripts/compile-content.mjs. Edit content/*.md, not this file.\nexport const generatedNews = ${JSON.stringify(newsArticles, null, 2)};\nexport const generatedPhotoReports = ${JSON.stringify(photoReports, null, 2)};\n`);
console.log(`Content compiled: ${newsArticles.length} news articles and ${photoReports.length} photo reports.`);
